[package]
name = "rpi_clock_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tauri = "1"
tao = "0"
wry = "0"
